site_name: MacroBase Documentation
docs_dir: source

pages:
  - Home: 'index.md'
  - MacroBase SQL:
    - 'Docs': 'sql/docs.md'
    - 'Setup': 'sql/setup.md'
    - 'Workshop': 'sql/workshop.md'
  - MacroBase GUI:
    - 'Setup': 'gui/setup.md'

theme:
  name: 'readthedocs'
